### ISSUE TITLE
Move application globals from redux to new global context

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/clinical-trials-search-app#346]
## As a developer, I want to move global application variables out of the redux store and into a global context so that CTS begins to resemble other app modules and to get the ball rolling on removing redux from CTS.

> **ESTIMATE** TBD

---

### Tasks
- [ ] Create global context and global context provider 
- [ ] Load app initialization variables into global context
- [ ] remove references to global variables throughout the application from redux to the new context
