### ISSUE TITLE
Update queryStringToFormObject utility function

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-search-app#381]
Utility function `queryStringToFormObject` is currently implemented in file `utilities/queryStringToFormObject.js`

Update this utility function:

**Parent Issue:** #362

> **ESTIMATE** 5

### Sub-Tasks
- [x]  Rename to `queryStringToSearchCriteria` (this includes 12 test files)
- [ ] Refactor useAppInitializer to move queryStringToSearchCriteria logic into trial description page and trial results page (useEffect and/or useCallback)
- [ ]  Pull the methods out of redux store
- [ ]  Make everything redux-independent
- [ ]  Dictate the shape of the generated form object
- [ ] Update unit tests for utility function
- [ ] Update the following integration test (/AdvancedSearchPage/LocationSection/LocationByZipcode.feature)
```gherkin
Scenario: Negative: User is not able to search for an incorrect zip code but is able to search for empty zip

Scenario: Negative: User is not able to search for an incorrect zip code AND is NOT able to search for empty zip
        Given the user navigates to "/about-cancer/treatment/clinical-trials/search/advanced"
        Then the page title is "Find NCI-Supported Clinical Trials"
        When user selects "ZIP Code" radio button
        When user types "999g9" in "U.S. ZIP Code" field
        Then alert "Please enter a valid 5 digit U.S. zip code" is displayed
        And user clicks on "Find Trials" button
        Then the search is not executed and path is "/about-cancer/treatment/clinical-trials/search/advanced"
        When user clears "U.S. ZIP Code" input field
        And user clicks on "Find Trials" button
        Then text "Sorry, you seem to have entered invalid criteria. Please check the following, and try your search again:" is displayed
        And the invalid criteria table displays the following
            | Criteria |
            | Zip      |
        And text "For assistance, please contact the Cancer Information Service. You can chat online or call 1-800-4-CANCER (1-800-422-6237)." is displayed
        And "chat online" has a link "https://livehelp.cancer.gov/app/chat/chat_landing"
        And "Try a new search" link has a href "/about-cancer/treatment/clinical-trials/search/advanced"
```
* this will act as a contract with the react-form search page object, they should match up
* Once this function is updated, we need to update everywhere that is calling this function, in order to make sure the entire app doesn't break

## NOTES:
This task should be updating https://github.com/NCIOCPL/clinical-trials-search-app/blob/develop/src/utilities/queryStringToFormObject.js. It looks like there need to be a few things taken into consideration:
1. `import { defaultState } from '../store/reducers/form';` will have to change because the reducer is going away.
    * this should be a copy of https://github.com/NCIOCPL/clinical-trials-search-app/blob/develop/src/store/reducers/form.js 
    * Remove:
       ```
        isDirty: false, // only updated after submission of either form
        zipModified: false,
        hasInvalidZip: false, // zip does not return coodinates
        refineSearch: false, //is the form in refine search mode
        ageModified: false,
        cancerTypeModified: false,
        subtypeModified: false,
        stagesModified: false,
        keywordPhrasesModified: false,
       ```       
2. The shape of the Object returned may not be the cleanest?
     * The unit tests are setup for that shape, so major changes might not be worth it.
3. The Label fetchers and Zip Code lat/long fetchers probably are ok, they are passed into the function anyway, and this should stay this way. (results and description page will need to pass in the fetchers and where they get them from is TBD and not part of this.)
