### ISSUE TITLE
Add methods from Clinical Trials Listing App

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-search-app#382]
We need to pull over methods from CTL (Listing App).

Clinical Trials Listings API from CTL (App already makes this call) - https://github.com/NCIOCPL/clinical-trials-listing-app/tree/develop/src/services/api/clinical-trials-search-api

**Parent Issue:** #362

> **ESTIMATE** 3

### Sub-Tasks
- [ ] Copy over methods from CTL 
- [ ] Add fetch call for clinical trials to `ResultsPage`
- [ ] The `useStoreToFindTrials` hook should be removed. The logic implemented above to fetch trials will replace that.
- [ ] Update unit tests for `ResultsPage`
- [ ] Implement Unit Tests for methods

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction
