### ISSUE TITLE
Create Proxy that handles the API key for v2 Clinical Trials API

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-search-app#389]
## As a developer, I want to create a proxy for the V2 Clinical Trials API, so that the API key can be passed through the command line instead of hardcoded in the app code.
> **ESTIMATE** 5

A proxy needs to be created in such that we can pass an API key in the command line in development, which then the proxy uses to verify when talking to the backend. This needs to be done, in order to avoid hardcoding in an API key in the code.

### Tasks
- [ ] Add the proxy from [Clinical Trials Listing App](https://github.com/NCIOCPL/clinical-trials-listing-app/blob/develop/support/src/setupProxy.js#L25)
- [ ] Update **ReadMe** AND DOCUMENT HOT TO CREATE for new set of mock API endpoints to live at `/cts/mock-api/v2`
        * DO NOT JUST REPLACE THE CURRENT SET OF MOCKS!! Create a new folder! _support/mock-data/cts/v2_ 
        * DO NOT IMPLEMENT ALL THE ENDPOINTS -- leave that up to the stories that implement the new endpoint. (You won't know what they are/or will be)
- [ ] Update the app to use a `ctsApiEndpointV2` parameter for connection to cts api v2
- [ ] Update how we choose to override the `ctsApiEndpointV2` to use in [index.js](https://github.com/NCIOCPL/clinical-trials-listing-app/blob/develop/src/index.js#L155)
       * USE CASES USING PUBLIC/index.html
          * If you are running against your local dev instance: `/cts/proxy-api/v2`
          * If you are running integration test: `/cts/mock-api/v2`
          * If you are running on react-app-dev: https://clinicaltrialsapi.cancer.gov/api/v2
       * DRUPAL
          * use the configuration's `ctsApiEndpointV2` property for the configuration passed in
- [ ] Update public.html for any changes.

The total changes for the listing app where this pattern was used was https://github.com/NCIOCPL/clinical-trials-listing-app/commit/4a4a0584f7d1f7d1a53910d97d7271ced1f09719

Parent Issue: #269

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Clinical Trials Listing App spike: https://github.com/NCIOCPL/clinical-trials-listing-app/issues/127
  * This has a lot of technical documentation about the overall implementation of V2 Clinical Trials API
* Clinical Trials Listing App story: https://github.com/NCIOCPL/clinical-trials-listing-app/issues/134

### Notes
*Some complementary notes if necessary:*

---

### Prerequisites
- See #269 for order of operations in updating to use V2 Clinical Trials API

### Technical Notes
- More notes, or technical nuances/direction
