### ISSUE TITLE
Update ResultsPage.jsx to use CTS API V2

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-search-app#390]
Tasks:

- [ ] Update searchApi/getClinicalTrials.js
- [ ] Update mock data and unit tests
- [ ] Update utility/formatTrialSearchQuery
- [ ] Update ResultsPage
  - [ ] Call the updated formatTrialSearchQuery
  - [ ] Update how we're checking trials to display
  - [ ] May have to update ResultsListItem

> **ESTIMATE** 5

### Acceptance Criteria

```gherkin

Scenario: User views the results page for a search for "all trials"
    Given the user navigates to "/about-cancer/treatment/clinical-trials/search/r?loc=0&rl=1"
    Then the page title is "Clinical Trials Search Results"
        And trial info displayes "Results 1-10  of 6821 for your search for: \"all trials\""
        And "Start Over" link has a href "/about-cancer/treatment/clinical-trials/search"
        And "Select all on page" checkbox displays
        And "Print Selected" button is displayed
        And the pager is displayed
        And results list is displayed
        And there are 2 delighters present
```

### Resources:
* Clinical Trials Listing App spike: https://github.com/NCIOCPL/clinical-trials-listing-app/issues/127
  *   This has a lot of technical documentation about the overall implementation of V2 Clinical Trials API
* Clinical Trials Listing App story: https://github.com/NCIOCPL/clinical-trials-listing-app/issues/135

### Notes

In the v2 of the api, there were multiple changes made to variables such as:

The API endpoint now returns the data as
```
{
  total: x,
  data: {},
}
```

Besides returning data in that new form, there is this schema change also:
```
{
  "central_contact": {
    "central_contact_phone": null,
    "central_contact_name": null,
    "central_contact_email": null,
    "central_contact_type": null
  }
}
```

To:
```
{
  "central_contact": {
    "phone": null,
    "name": null,
    "type": null,
    "email": null
  }
}
```

Besides these two changes, there are many more listed in this document:
https://clinicaltrialsapi.cancer.gov/breaking-changes

All instances of these changed variables must be updated.

---

### Prerequisites
- See #269 for order of operations in updating to use V2 Clinical Trials API

### Tasks
- [ ] Go through the breaking changes doc, and change variables accordingly
- [ ] Update any tests accordingly

### Technical Notes
- More notes, or technical nuances/direction
