### ISSUE TITLE
Build CTS v2 Middleware to implement new fetchers

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-search-app#416]
New fetchers will be implemented for CTS v2.  In order to use these fetchers, we will need to update middleware to handle and apply the new fetchers.  Basically, we will take a copy of the v1 middleware, pare it down to just what we need (no more transforming responses) and rebrand it (`action.type !== '@@api/CTSv2'`).  

> **ESTIMATE** 5
------------
For sprint 8:
> **ESTIMATE** 1

**Parent Issue:** #406

### Sub-Tasks
- [x] make a copy of CTSMiddleware.js (to be named CTSMiddlewareV2.js and change the action type to `@@api/CTSv2`
- [x] add the new middleware to src/index.js and add to middleware chain in store creation
- [ ] create actionsV2.js in `src/store`
  - [ ] create reducer for actions (giant switch statement for fetchers); do any necessary transformation here
- [ ] need to make sure redux cache store is being updated

### Notes
* get rid of fetch handlers; transformation should happen in the actions switch?
*  create new actions file so that it can be moved around and just imported into `CTSMiddlewareV2.js`

**Comment by sarinapadilla** [comment]
@arcepaul please fill out this ticket by COB 11/23/21

**Comment by sarinapadilla** [comment]
Closed with PR #450, so closing this ticket.
