### ISSUE TITLE
Refactor Cypress Step Definitions to Reduce Duplication 

### ISSUE THREAD

**Issue by adriancofie** [NCIOCPL/clinical-trials-search-app#629]
Currently our version of cypress-cucumber-preprocessor is far outdated and has some inherent deficiencies which required structuring the tests in a non-intuitive fashion.  

This ticket is to update the pre-processor to the latest version (Note: the project maintainer changed hand a while ago and it's now @badeball/cypress-cucumber-preprocessor), and refactor the test cases to follow best practices where ideal.

There have been several breaking changes in the preprocessor  and the version is now at [v20.0.5](https://github.com/badeball/cypress-cucumber-preprocessor/releases/tag/v20.0.5)  while we are at v4.  We don't need to upgrade to the latest version but we should at the very least update to a version that allows us to have a sane directory structure. 

Newer version follow a well defined approach for matching step definitons:

https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/step-definitions.md

---
Note:

We currently have several duplicated step definitions, in the version we're using the preprocessor uses the first step definition it finds and ignores the rest, however looking statically at the cod  a developer would have no idea which definition to update in order make changes, nor know which one not to change in order not to break something.  

In later versions the preprocessor was updated to  explicitly disallow step definitions from having duplicates-- this is the approach that cucumber itself follows (https://cucumber.io/docs/community/faq/?lang=java#duplicate-step-definition). Note this applies across defineStep types ('Given', 'Then' etc).

---

Note:

From version 13.0.0 onward the support for AND and BUT is removed.

https://github.com/badeball/cypress-cucumber-preprocessor/issues/821

See Release Notes for v13.0.0 https://github.com/badeball/cypress-cucumber-preprocessor/releases

---

This ticket fixes : 

1. Code duplication / confusion
2. Over usage of anonymous functions ---> there are several locations where we should have a generic step with a function that gets overridden. This allows different logic for different components without the duplication.  OR even better --- the step differentiated for different components should be differentiated where possible.

### Sub-Tasks
- [ ] Update the preprocessor 
- [ ] Update the config and pattern matching for the preprocessor -- pull it out of package.json
- [ ] Restructure features so they live in the same folder as their isolated step defintions
- [ ] Move the location of common cross cutting step definitions
- [ ] Deduplicate step definitions and move common ones to the same location 
   - [ ] If a step would preferably keep the same gherkin but has different logic for a specific component then the function itself should be abstracted and overrides
